/*
Bruce Black
Software Development
CSIS 505
Leader Tracker
July 4, 2021
 */
package solutions.adapttech.leadertracker;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

public class HomeJFrame extends javax.swing.JFrame {

    public HomeJFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personJScrollPane = new javax.swing.JScrollPane();
        personJList = new javax.swing.JList<>();
        equipmentJScrollPane = new javax.swing.JScrollPane();
        equipmentJList = new javax.swing.JList<>();
        taskingJScrollPane = new javax.swing.JScrollPane();
        taskingJList = new javax.swing.JList<>();
        trainingJScrollPane = new javax.swing.JScrollPane();
        trainingJList = new javax.swing.JList<>();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        personJButton = new javax.swing.JButton();
        equipmentJButton = new javax.swing.JButton();
        taskingJButton = new javax.swing.JButton();
        trainingJButton1 = new javax.swing.JButton();
        getPersonJButton = new javax.swing.JButton();
        getEquipmentJButton = new javax.swing.JButton();
        getTaskingJButton = new javax.swing.JButton();
        getTrainingJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "SSG Black", "SSG White", "PVT Brown" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        personJScrollPane.setViewportView(personJList);

        equipmentJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Truck", "Laptop", "Monitor" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        equipmentJScrollPane.setViewportView(equipmentJList);

        taskingJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Staff Duty", "CQ" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        taskingJScrollPane.setViewportView(taskingJList);

        trainingJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Weapons Range", "Obstacle Course" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        trainingJScrollPane.setViewportView(trainingJList);

        personJButton.setText("Add/Edit/Delete Person");
        personJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personJButtonActionPerformed(evt);
            }
        });

        equipmentJButton.setText("Add/Edit/Delete Equipment");
        equipmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentJButtonActionPerformed(evt);
            }
        });

        taskingJButton.setText("Add/Edit/Delete Tasking");
        taskingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskingJButtonActionPerformed(evt);
            }
        });

        trainingJButton1.setText("Add/Edit/Delete Training");
        trainingJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainingJButton1ActionPerformed(evt);
            }
        });

        getPersonJButton.setText("Get People");
        getPersonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPersonJButtonActionPerformed(evt);
            }
        });

        getEquipmentJButton.setText("Get Equipment");
        getEquipmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getEquipmentJButtonActionPerformed(evt);
            }
        });

        getTaskingJButton.setText("Get Tasking");
        getTaskingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTaskingJButtonActionPerformed(evt);
            }
        });

        getTrainingJButton.setText("Get Training");
        getTrainingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTrainingJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(getPersonJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(getEquipmentJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(personJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equipmentJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(taskingJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(getTaskingJButton)
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trainingJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(getTrainingJButton))))
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personJButton)
                    .addComponent(equipmentJButton)
                    .addComponent(taskingJButton)
                    .addComponent(trainingJButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(taskingJScrollPane)
                            .addComponent(equipmentJScrollPane)
                            .addComponent(trainingJScrollPane)
                            .addComponent(personJScrollPane))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getPersonJButton)
                            .addComponent(getEquipmentJButton)
                            .addComponent(getTaskingJButton)
                            .addComponent(getTrainingJButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(personJButton)
                        .addGap(18, 18, 18)
                        .addComponent(equipmentJButton)
                        .addGap(18, 18, 18)
                        .addComponent(taskingJButton)
                        .addGap(18, 18, 18)
                        .addComponent(trainingJButton1)))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personJButtonActionPerformed
        new CreateEditDeletePersonJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_personJButtonActionPerformed

    private void equipmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentJButtonActionPerformed
        new CreateEditDeleteEquipmentJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_equipmentJButtonActionPerformed

    private void taskingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskingJButtonActionPerformed
        new CreateEditDeleteTaskingJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_taskingJButtonActionPerformed

    private void trainingJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainingJButton1ActionPerformed
        new CreateEditDeleteTrainingJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_trainingJButton1ActionPerformed
    DefaultListModel modEquipment = new DefaultListModel();
    private void getEquipmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getEquipmentJButtonActionPerformed
        equipmentJList.setModel(modEquipment);

        modEquipment.addElement("Truck");
        modEquipment.addElement("Weapon");
        modEquipment.addElement("Computer");
    }//GEN-LAST:event_getEquipmentJButtonActionPerformed
    DefaultListModel modPeople = new DefaultListModel();
    private void getPersonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPersonJButtonActionPerformed
        personJList.setModel(modPeople);

        modPeople.addElement("SSG Black");
        modPeople.addElement("SSG Brown");
        modPeople.addElement("SSG White");

    }//GEN-LAST:event_getPersonJButtonActionPerformed
    DefaultListModel modTasking = new DefaultListModel();
    private void getTaskingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTaskingJButtonActionPerformed
        taskingJList.setModel(modTasking);

        modTasking.addElement("CQ 20210704");
        modTasking.addElement("Staff Duty 20210801");
        modTasking.addElement("Cleanup 20210802");
    }//GEN-LAST:event_getTaskingJButtonActionPerformed
    DefaultListModel modTraining = new DefaultListModel();
    private void getTrainingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTrainingJButtonActionPerformed
        trainingJList.setModel(modTraining);

        modTraining.addElement("Range 20210704");
        modTraining.addElement("Obstacle Course 20210801");
        modTraining.addElement("Land Navigation 20210802");
    }//GEN-LAST:event_getTrainingJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new HomeJFrame().setVisible(true);

            }

            Person black = new Person(01, "Black", "Bruce", "SSG", 19880213, 20201201, 'A', "", 5551234, "bruceblack88@gmail.com", "123 Street");
            Person brown = new Person(02, "Brown", "Brian", "SFC", 19900213, 20201101, 'U', "", 5551235, "bruceblack88@gmail.com", "124 Street");
            Person white = new Person(03, "White", "Brandon", "PVT", 20000213, 202011001, 'A', "", 5551236, "bruceblack88@gmail.com", "125 Street");

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton equipmentJButton;
    private javax.swing.JList<String> equipmentJList;
    private javax.swing.JScrollPane equipmentJScrollPane;
    private javax.swing.JButton getEquipmentJButton;
    private javax.swing.JButton getPersonJButton;
    private javax.swing.JButton getTaskingJButton;
    private javax.swing.JButton getTrainingJButton;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JButton personJButton;
    private javax.swing.JList<String> personJList;
    private javax.swing.JScrollPane personJScrollPane;
    private javax.swing.JButton taskingJButton;
    private javax.swing.JList<String> taskingJList;
    private javax.swing.JScrollPane taskingJScrollPane;
    private javax.swing.JButton trainingJButton1;
    private javax.swing.JList<String> trainingJList;
    private javax.swing.JScrollPane trainingJScrollPane;
    // End of variables declaration//GEN-END:variables
}
